### ISSUE TITLE
JavaScript Events Quiz. Question 9 error 

### ISSUE THREAD

**Issue by kirby885** [learn-co-curriculum/phase-1-quiz-javascript-events#8]
Question 9 marked me wrong even thought i typed the exact same thing in my 2nd pass through of the test and there for i thought i was wrong and typed something that was actual wrong....
what i wrote was -----> form.addEventListener('submit', logSubmit);
I'm hoping that this will reach the correct people so they can hopefully fix it not only for my-sake but all the other students who may face the same issue. 
  
Please fix or add this version of the code for I'm certain it should work. 
------->
form.addEventListener('submit', logSubmit);

**Comment by codified45** [comment]
I typed this exact line and it worked:
`form.addEventListener('submit', logSubmit)`
Has this been fixed? Or is this because I omitted the semicolon (which should also be correct)?

**Comment by lizbur10** [comment]
Hello @kirby885 and @codified45 ! It looks like this issue was fixed quite a while ago (back in May). @kirby885 my guess is that the version of the quiz in your Canvas course could not be updated because some students had already taken the quiz. Canvas will not allow certain changes to a quiz if students have completed it. The response you both tried is one of the listed correct responses. 

Thanks for contributing to the Flatiron School curriculum 💙
